apiVersion: operatorfwk.felipe88alves/v1alpha2
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: service-sample
    app.kubernetes.io/part-of: operator-fwk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator-fwk
  name: service-sample
spec:
  # TODO(user): Add fields here
